/* Creative dashboard logic - localStorage CMS */
const K = {
  users:'chemcode_users', current:'chemcode_current_user', lessons:'chemcode_lessons', questions:'chemcode_questions', quizzes:'chemcode_quizzes', files:'chemcode_files', codes:'chemcode_activation_codes', adminPin:'chemcode_admin_pin', settings:'chemcode_settings'
};
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
const uid = p => `${p}-${Date.now()}-${Math.random().toString(16).slice(2,7)}`;
function get(k, fallback=[]){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(fallback))}catch{return fallback}}
function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
function toast(msg){let t=$('.toast')||document.body.appendChild(Object.assign(document.createElement('div'),{className:'toast'}));t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function currentUser(){const email=localStorage.getItem(K.current);return get(K.users).find(u=>u.email===email)||null}
function saveUsers(u){set(K.users,u)}
function initialData(){
  if(!localStorage.getItem(K.lessons)) set(K.lessons,[
    {id:'1',icon:'⚗️',title:'Mole Code',titleAr:'شفرة المول',description:'Convert between mole, mass and particles.',grade:'grade2',access:'free',duration:'15 min',level:'Beginner',videoUrl:'',pdfUrl:'',htmlContent:''},
    {id:'2',icon:'⚛️',title:'Atomic Structure Code',titleAr:'شفرة التركيب الذري',description:'Protons, neutrons, electrons and atomic number.',grade:'grade2',access:'monthly',duration:'20 min',level:'Beginner',videoUrl:'',pdfUrl:'',htmlContent:''},
    {id:'6',icon:'🧫',title:'Organic Reactions Code',titleAr:'شفرة التفاعلات العضوية',description:'Mind map for organic reactions.',grade:'grade3',access:'vip',duration:'35 min',level:'Advanced',videoUrl:'',pdfUrl:'',htmlContent:''}
  ]);
  if(!localStorage.getItem(K.questions)) set(K.questions,[]);
  if(!localStorage.getItem(K.files)) set(K.files,[]);
  if(!localStorage.getItem(K.quizzes)) set(K.quizzes,[]);
  if(!localStorage.getItem(K.codes)) set(K.codes,[]);
  if(!localStorage.getItem(K.adminPin)) localStorage.setItem(K.adminPin,'CHEM2026');
}
function requireAdmin(){
  if(sessionStorage.getItem('chem_admin_ok')==='1') return true;
  document.body.innerHTML = `<div class="dash-watermark"></div><div class="lock"><div class="lock-card"><div class="brand-icon" style="margin:auto">🛡️</div><h1>Admin Control Center</h1><p class="muted">Enter admin PIN. Default: <b>CHEM2026</b></p><input id="pin" type="password" placeholder="Admin PIN" style="text-align:center;font-size:1.2rem"><br><br><button class="btn" onclick="checkAdminPin()">Enter Dashboard 🚀</button><p style="margin-top:18px"><a class="btn secondary small" href="index.html">Back home</a></p></div></div><div class="toast"></div>`;
  window.checkAdminPin=()=>{if($('#pin').value===localStorage.getItem(K.adminPin)){sessionStorage.setItem('chem_admin_ok','1');location.reload()}else toast('Wrong PIN')};
  return false;
}
function activateNav(id){$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));location.hash=id}
function bindNav(){ $$('.nav button[data-panel]').forEach(b=>b.onclick=()=>activateNav(b.dataset.panel)); const h=location.hash.slice(1); if(h&&$('#'+h)) activateNav(h); }
function openModal(title, body, footer=''){ $('#modalTitle').textContent=title; $('#modalBody').innerHTML=body; $('#modalFoot').innerHTML=footer; $('#modal').classList.add('active') }
function closeModal(){ $('#modal').classList.remove('active') }
window.closeModal=closeModal;
function collectForm(form){return Object.fromEntries(new FormData(form).entries())}
function planPill(plan){return `<span class="pill ${plan==='vip'?'vip':plan==='free'?'free':''}">${esc(plan||'free')}</span>`}
function canAccess(user, lesson){ if(!user) return lesson.access==='free'; if(user.plan==='vip') return true; if(user.plan==='monthly') return lesson.access!=='vip'; return lesson.access==='free'; }

/* Admin render */
function renderAdmin(){
  renderStats(); renderUsers(); renderLessons(); renderQuestions(); renderQuizzes(); renderFiles(); renderCodes(); renderSettings();
}
function renderStats(){
  const users=get(K.users), lessons=get(K.lessons), qs=get(K.questions), codes=get(K.codes), files=get(K.files);
  $('#stats').innerHTML = [
    ['👥',users.length,'Students'],['🎥',lessons.length,'Lessons'],['❓',qs.length,'Questions'],['🎟️',codes.filter(c=>!c.used).length,'Active codes'],['📁',files.length,'Files']
  ].map(s=>`<div class="stat"><div class="num">${s[0]} ${s[1]}</div><div class="label">${s[2]}</div></div>`).join('');
}
function renderUsers(){
  const users=get(K.users);
  $('#usersTable').innerHTML = `<table><thead><tr><th>Name</th><th>Email</th><th>Grade</th><th>Plan</th><th>Joined</th><th>Actions</th></tr></thead><tbody>${users.map((u,i)=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${esc(u.grade)}</td><td>${planPill(u.plan)}</td><td>${new Date(u.joinDate||Date.now()).toLocaleDateString()}</td><td class="toolbar"><button class="btn small" onclick="editUser(${i})">Edit</button><button class="btn danger small" onclick="deleteUser(${i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No students yet</td></tr>'}</tbody></table>`;
}
window.editUser=i=>{const u=get(K.users)[i];openModal('Edit student',`<form id="userForm" class="form-grid"><div class="field"><label>Name</label><input name="name" value="${esc(u.name)}"></div><div class="field"><label>Email</label><input name="email" value="${esc(u.email)}"></div><div class="field"><label>Grade</label><input name="grade" value="${esc(u.grade||'')}"></div><div class="field"><label>Plan</label><select name="plan"><option ${u.plan==='free'?'selected':''}>free</option><option ${u.plan==='monthly'?'selected':''}>monthly</option><option ${u.plan==='vip'?'selected':''}>vip</option></select></div><div class="field"><label>Password</label><input name="password" value="${esc(u.password||'')}"></div></form>`,`<button class="btn" onclick="saveUser(${i})">Save</button>`)};
window.saveUser=i=>{let users=get(K.users);users[i]={...users[i],...collectForm($('#userForm'))};saveUsers(users);closeModal();renderAdmin();toast('Student saved')};
window.deleteUser=i=>{if(confirm('Delete student?')){let a=get(K.users);a.splice(i,1);saveUsers(a);renderAdmin();toast('Student deleted')}};
function lessonForm(l={}){return `<form id="lessonForm" class="form-grid"><div class="field"><label>ID</label><input name="id" value="${esc(l.id||uid('lesson'))}" required></div><div class="field"><label>Icon</label><input name="icon" value="${esc(l.icon||'📚')}"></div><div class="field"><label>English title</label><input name="title" value="${esc(l.title||'')}"></div><div class="field"><label>Arabic title</label><input name="titleAr" value="${esc(l.titleAr||'')}"></div><div class="field full"><label>Description</label><textarea name="description">${esc(l.description||'')}</textarea></div><div class="field"><label>Grade</label><select name="grade"><option value="grade2">Grade 2</option><option value="grade3">Grade 3</option></select></div><div class="field"><label>Access</label><select name="access"><option value="free">Free</option><option value="monthly">Monthly</option><option value="vip">VIP</option></select></div><div class="field"><label>Duration</label><input name="duration" value="${esc(l.duration||'')}"></div><div class="field"><label>Level</label><input name="level" value="${esc(l.level||'Intermediate')}"></div><div class="field full"><label>Video URL</label><input name="videoUrl" value="${esc(l.videoUrl||'')}"></div><div class="field full"><label>PDF / File URL</label><input name="pdfUrl" value="${esc(l.pdfUrl||'')}"></div><div class="field full"><label>HTML lesson content</label><textarea name="htmlContent" style="min-height:180px">${esc(l.htmlContent||'')}</textarea></div><div class="field full"><label>Import HTML file into content</label><input type="file" accept=".html,.htm,.txt" onchange="readLessonHtml(this)"></div></form><script>setTimeout(()=>{let f=document.getElementById('lessonForm'); if(f){f.grade.value='${l.grade||'grade2'}';f.access.value='${l.access||'free'}'}},0)</script>`}
window.readLessonHtml=input=>{const file=input.files[0]; if(!file)return; const r=new FileReader(); r.onload=()=>{$('#lessonForm textarea[name=htmlContent]').value=r.result}; r.readAsText(file)};
function renderLessons(){const lessons=get(K.lessons); $('#lessonsTable').innerHTML=`<table><thead><tr><th>Lesson</th><th>Grade</th><th>Access</th><th>Duration</th><th>Actions</th></tr></thead><tbody>${lessons.map((l,i)=>`<tr><td><b>${esc(l.icon)} ${esc(l.title)}</b><br><span class="muted">${esc(l.titleAr||'')}</span></td><td>${esc(l.grade)}</td><td>${planPill(l.access)}</td><td>${esc(l.duration)}</td><td class="toolbar"><button class="btn small" onclick="editLesson(${i})">Edit</button><button class="btn secondary small" onclick="previewLesson(${i})">Preview</button><button class="btn danger small" onclick="deleteLesson(${i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No lessons</td></tr>'}</tbody></table>`}
window.addLesson=()=>openModal('Add lesson',lessonForm(),`<button class="btn" onclick="saveLesson()">Create lesson</button>`);
window.editLesson=i=>openModal('Edit lesson',lessonForm(get(K.lessons)[i]),`<button class="btn" onclick="saveLesson(${i})">Save lesson</button>`);
window.saveLesson=i=>{let a=get(K.lessons), data=collectForm($('#lessonForm')); if(i===undefined)a.push(data);else a[i]={...a[i],...data}; set(K.lessons,a); closeModal(); if(document.body.dataset.dashboard==='admin') renderAdmin(); if(document.body.dataset.dashboard==='lessons') renderLessonsDashboard(); toast('Lesson saved')};
window.deleteLesson=i=>{if(confirm('Delete lesson?')){let a=get(K.lessons);a.splice(i,1);set(K.lessons,a); if(document.body.dataset.dashboard==='admin') renderAdmin(); if(document.body.dataset.dashboard==='lessons') renderLessonsDashboard();toast('Lesson deleted')}};
window.previewLesson=i=>{const l=get(K.lessons)[i];openModal(l.title,`<div class="lesson-tile"><h2>${esc(l.icon)} ${esc(l.title)}</h2><p>${esc(l.description)}</p><div>${l.htmlContent||'<span class="muted">No HTML content</span>'}</div></div>`)};
function questionForm(q={}){return `<form id="questionForm" class="form-grid"><div class="field"><label>Type</label><select name="type"><option value="multiple-choice">Multiple Choice</option><option value="true-false">True/False</option><option value="fill-blank">Fill Blank</option></select></div><div class="field"><label>Category</label><input name="category" value="${esc(q.category||'basics')}"></div><div class="field"><label>Difficulty</label><select name="difficulty"><option>easy</option><option>medium</option><option>hard</option></select></div><div class="field"><label>Correct answer</label><input name="answer" value="${esc(q.answer||'')}"></div><div class="field full"><label>Question text</label><textarea name="text">${esc(q.text||'')}</textarea></div><div class="field full"><label>Options - one per line. Put * before correct option.</label><textarea name="options">${esc((q.options||[]).map(o=>(o.correct?'*':'')+o.text).join('\n'))}</textarea></div><div class="field full"><label>Explanation</label><textarea name="explanation">${esc(q.explanation||'')}</textarea></div></form><script>setTimeout(()=>{let f=document.getElementById('questionForm'); if(f){f.type.value='${q.type||'multiple-choice'}';f.difficulty.value='${q.difficulty||'easy'}'}},0)</script>`}
function parseQuestionForm(){let d=collectForm($('#questionForm'));d.id=d.id||uid('q');d.options=(d.options||'').split('\n').filter(Boolean).map(line=>({text:line.replace(/^\*/,''),correct:line.startsWith('*')})); if(!d.answer){let c=d.options.find(o=>o.correct);d.answer=c?c.text:''} return d}
function renderQuestions(){const qs=get(K.questions); $('#questionsTable').innerHTML=`<table><thead><tr><th>Question</th><th>Type</th><th>Category</th><th>Answer</th><th>Actions</th></tr></thead><tbody>${qs.map((q,i)=>`<tr><td>${esc(q.text).slice(0,160)}</td><td>${esc(q.type)}</td><td>${esc(q.category)} / ${esc(q.difficulty)}</td><td class="success-text">${esc(q.answer)}</td><td class="toolbar"><button class="btn small" onclick="editQuestion(${i})">Edit</button><button class="btn danger small" onclick="deleteQuestion(${i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No questions yet. Import HTML or add manually.</td></tr>'}</tbody></table>`}
window.addQuestion=()=>openModal('Add question',questionForm(),`<button class="btn" onclick="saveQuestion()">Save question</button>`);
window.editQuestion=i=>openModal('Edit question',questionForm(get(K.questions)[i]),`<button class="btn" onclick="saveQuestion(${i})">Save question</button>`);
window.saveQuestion=i=>{let a=get(K.questions), q=parseQuestionForm(); if(i===undefined)a.push(q);else a[i]={...a[i],...q}; set(K.questions,a);closeModal();renderAdmin();toast('Question saved')};
window.deleteQuestion=i=>{if(confirm('Delete question?')){let a=get(K.questions);a.splice(i,1);set(K.questions,a);renderAdmin();toast('Question deleted')}};
window.importQuestionsHtml=input=>{const file=input.files[0]; if(!file)return; const r=new FileReader(); r.onload=()=>{const doc=new DOMParser().parseFromString(r.result,'text/html'); const parsed=[...doc.querySelectorAll('.question')].map(el=>{let opts=[...el.querySelectorAll('.option')].map(o=>({text:o.textContent.trim(),correct:o.classList.contains('correct')}));let ans=el.querySelector('.q-answer')?.textContent.trim()||opts.find(o=>o.correct)?.text||'';return{id:uid('q'),type:el.dataset.type||'multiple-choice',category:el.dataset.category||'general',difficulty:el.dataset.difficulty||'easy',text:el.querySelector('.q-text')?.textContent.trim()||el.textContent.trim().slice(0,200),options:opts,answer:ans,explanation:''}}); set(K.questions,get(K.questions).concat(parsed));renderAdmin();toast(`Imported ${parsed.length} questions`)}; r.readAsText(file)};
function renderQuizzes(){const quizzes=get(K.quizzes), qs=get(K.questions); $('#quizzesTable').innerHTML=`<table><thead><tr><th>Quiz</th><th>Questions</th><th>Duration</th><th>Points</th><th>Actions</th></tr></thead><tbody>${quizzes.map((q,i)=>`<tr><td>${esc(q.icon||'📝')} <b>${esc(q.title)}</b></td><td>${(q.questions||[]).length}</td><td>${esc(q.duration||10)} min</td><td>${esc(q.points||50)}</td><td class="toolbar"><button class="btn small" onclick="editQuiz(${i})">Edit</button><button class="btn danger small" onclick="deleteQuiz(${i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No quizzes</td></tr>'}</tbody></table>`; $('#quizQuestionPicker')&&($('#quizQuestionPicker').innerHTML=qs.map(q=>`<option value="${q.id}">${esc(q.text).slice(0,80)}</option>`).join(''))}
function quizForm(q={}){const qs=get(K.questions);return `<form id="quizForm" class="form-grid"><div class="field"><label>Title</label><input name="title" value="${esc(q.title||'New Quiz')}"></div><div class="field"><label>Icon</label><input name="icon" value="${esc(q.icon||'📝')}"></div><div class="field"><label>Duration minutes</label><input name="duration" type="number" value="${esc(q.duration||10)}"></div><div class="field"><label>Points</label><input name="points" type="number" value="${esc(q.points||50)}"></div><div class="field full"><label>Select questions</label><select id="quizQs" multiple size="10">${qs.map(x=>`<option value="${x.id}" ${(q.questionIds||[]).includes(x.id)?'selected':''}>${esc(x.text).slice(0,120)}</option>`).join('')}</select></div></form>`}
window.addQuiz=()=>openModal('Create quiz',quizForm(),`<button class="btn" onclick="saveQuiz()">Save quiz</button>`);
window.editQuiz=i=>openModal('Edit quiz',quizForm(get(K.quizzes)[i]),`<button class="btn" onclick="saveQuiz(${i})">Save quiz</button>`);
window.saveQuiz=i=>{let a=get(K.quizzes), d=collectForm($('#quizForm')), ids=[...$('#quizQs').selectedOptions].map(o=>o.value), qs=get(K.questions); d.id=d.id||uid('quiz'); d.questionIds=ids; d.questions=qs.filter(q=>ids.includes(q.id)); if(i===undefined)a.push(d);else a[i]={...a[i],...d}; set(K.quizzes,a);closeModal();renderAdmin();toast('Quiz saved')};
window.deleteQuiz=i=>{if(confirm('Delete quiz?')){let a=get(K.quizzes);a.splice(i,1);set(K.quizzes,a);renderAdmin();toast('Quiz deleted')}};
function renderFiles(){const files=get(K.files); $('#filesTable').innerHTML=`<table><thead><tr><th>File</th><th>Type</th><th>Size</th><th>Actions</th></tr></thead><tbody>${files.map((f,i)=>`<tr><td><b>${esc(f.name)}</b><br><span class="muted">${new Date(f.createdAt).toLocaleString()}</span></td><td>${esc(f.type)}</td><td>${Math.round((f.size||0)/1024)} KB</td><td class="toolbar"><button class="btn small" onclick="viewFile(${i})">View</button><button class="btn secondary small" onclick="downloadFile(${i})">Download</button><button class="btn danger small" onclick="deleteFile(${i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="4" class="muted">No files uploaded</td></tr>'}</tbody></table>`}
window.uploadFiles=input=>{[...input.files].forEach(file=>{const r=new FileReader();r.onload=()=>{let files=get(K.files);files.push({id:uid('file'),name:file.name,type:file.type||'file',size:file.size,content:r.result,createdAt:new Date().toISOString()});set(K.files,files);renderAdmin();toast('File uploaded')};r.readAsDataURL(file)})};
window.viewFile=i=>{const f=get(K.files)[i]; const body=f.type.startsWith('image/')?`<img src="${f.content}" style="max-width:100%;border-radius:18px">`:f.type.includes('html')?`<iframe src="${f.content}" style="width:100%;height:70vh;border:0;border-radius:18px;background:white"></iframe>`:`<p class="muted">Preview unavailable. Use download.</p>`; openModal(f.name,body)};
window.downloadFile=i=>{const f=get(K.files)[i], a=document.createElement('a');a.href=f.content;a.download=f.name;a.click()};
window.deleteFile=i=>{if(confirm('Delete file?')){let a=get(K.files);a.splice(i,1);set(K.files,a);renderAdmin();toast('File deleted')}};
function renderCodes(){const codes=get(K.codes); $('#codesBox').innerHTML=`<div class="code-list">${codes.slice().reverse().map((c,ri)=>{const i=codes.length-1-ri;return `<div class="code-card"><div>${esc(c.code)}</div><div class="muted">${esc(c.plan)} • ${c.used?'Used':'Available'}</div><div class="toolbar" style="margin-top:8px"><button class="btn danger small" onclick="deleteCode(${i})">Delete</button></div></div>`}).join('')||'<p class="muted">No codes generated yet</p>'}</div>`}
function randomCode(prefix){return `${prefix}-${Math.random().toString(36).slice(2,6).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`}
window.generateCodes=()=>{const count=+$('#codeCount').value||1, plan=$('#codePlan').value, prefix=$('#codePrefix').value||plan.toUpperCase(); let codes=get(K.codes); for(let i=0;i<count;i++) codes.push({code:randomCode(prefix),plan,used:false,createdAt:new Date().toISOString()}); set(K.codes,codes);renderAdmin();toast(`${count} codes generated`)};
window.deleteCode=i=>{let a=get(K.codes);a.splice(i,1);set(K.codes,a);renderAdmin()};
window.exportCodes=()=>downloadText('activation-codes.csv','code,plan,used,usedBy\n'+get(K.codes).map(c=>`${c.code},${c.plan},${c.used},${c.usedBy||''}`).join('\n'));
function renderSettings(){const s=get(K.settings,{}); $('#settingsBox').innerHTML=`<div class="form-grid"><div class="field"><label>Admin PIN</label><input id="newPin" value="${esc(localStorage.getItem(K.adminPin)||'CHEM2026')}"></div><div class="field"><label>Site notice</label><input id="siteNotice" value="${esc(s.notice||'')}"></div><div class="field full"><button class="btn" onclick="saveSettings()">Save settings</button></div></div>`}
window.saveSettings=()=>{localStorage.setItem(K.adminPin,$('#newPin').value);set(K.settings,{notice:$('#siteNotice').value});toast('Settings saved')};
function downloadText(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.exportAll=()=>downloadText('chemistry-dashboard-backup.json',JSON.stringify({users:get(K.users),lessons:get(K.lessons),questions:get(K.questions),quizzes:get(K.quizzes),files:get(K.files),codes:get(K.codes),settings:get(K.settings,{})},null,2));
window.importAll=input=>{const file=input.files[0]; if(!file)return; const r=new FileReader();r.onload=()=>{const d=JSON.parse(r.result);Object.entries({users:K.users,lessons:K.lessons,questions:K.questions,quizzes:K.quizzes,files:K.files,codes:K.codes,settings:K.settings}).forEach(([key,store])=>{if(d[key])set(store,d[key])});renderAdmin();toast('Backup imported')};r.readAsText(file)};
window.resetDemo=()=>{if(confirm('Reset lessons/questions/files/codes?')){[K.lessons,K.questions,K.quizzes,K.files,K.codes].forEach(k=>localStorage.removeItem(k));initialData();renderAdmin();toast('Demo reset')}};

/* Student */
function renderStudent(){const u=currentUser(); if(!u){$('.main').innerHTML='<div class="hero"><h1>Please login first</h1><p class="muted">Create an account or login to view your dashboard.</p><a class="btn" href="login.html">Login</a></div>';return} $('#studentName').textContent=u.name; $('#studentPlan').innerHTML=planPill(u.plan); const lessons=get(K.lessons), quizzes=get(K.quizzes), files=get(K.files); $('#studentStats').innerHTML=[['Plan',u.plan],['Available lessons',lessons.filter(l=>canAccess(u,l)).length],['Quizzes',quizzes.length],['Files',files.length]].map(x=>`<div class="stat"><div class="num">${esc(x[1])}</div><div class="label">${esc(x[0])}</div></div>`).join(''); $('#studentLessons').innerHTML=lessons.map(l=>`<div class="lesson-tile"><h3>${esc(l.icon)} ${esc(l.title)}</h3><p>${esc(l.description)}</p><p>${planPill(l.access)} <span class="pill">${esc(l.duration)}</span></p>${canAccess(u,l)?`<button class="btn small" onclick="studentViewLesson('${l.id}')">Open lesson</button>`:`<a class="btn secondary small" href="pricing.html">Upgrade</a>`}</div>`).join(''); $('#studentFiles').innerHTML=files.map((f,i)=>`<div class="lesson-tile"><h3>📁 ${esc(f.name)}</h3><button class="btn small" onclick="downloadStudentFile(${i})">Download</button></div>`).join('')||'<p class="muted">No files yet</p>'}
window.studentViewLesson=id=>{const l=get(K.lessons).find(x=>x.id==id);openModal(l.title,`<h2>${esc(l.icon)} ${esc(l.title)}</h2><p>${esc(l.description)}</p>${l.videoUrl?`<p><a class="btn" href="${esc(l.videoUrl)}" target="_blank">Open video</a></p>`:''}${l.pdfUrl?`<p><a class="btn secondary" href="${esc(l.pdfUrl)}" target="_blank">Open PDF/file</a></p>`:''}<div>${l.htmlContent||''}</div>`)};
window.downloadStudentFile=i=>downloadFile(i);

/* Lessons-only dashboard */
function renderLessonsDashboard(){renderLessons(); const lessons=get(K.lessons); $('#lessonCards')&&($('#lessonCards').innerHTML=lessons.map((l,i)=>`<div class="lesson-tile"><h3>${esc(l.icon)} ${esc(l.title)}</h3><p>${esc(l.description)}</p><p>${planPill(l.access)} <span class="pill">${esc(l.grade)}</span></p><div class="toolbar"><button class="btn small" onclick="editLesson(${i})">Edit</button><button class="btn secondary small" onclick="previewLesson(${i})">Preview</button><button class="btn danger small" onclick="deleteLesson(${i})">Delete</button></div></div>`).join(''))}

function init(){initialData(); const type=document.body.dataset.dashboard; if(type==='admin'){if(!requireAdmin())return; bindNav(); renderAdmin()} if(type==='student'){renderStudent()} if(type==='lessons'){if(!requireAdmin())return; renderLessonsDashboard()} }
document.addEventListener('DOMContentLoaded',init);
